#
# The bountybase configuration: This is yaml.

# The syslog configuration, per environment an array of [ hostname, port ] 
syslog:
  deployment:
    - logs.papertrailapp.com
    - 61566
  live:
    - logs.papertrailapp.com
    - 11905
  staging:
    - logs.papertrailapp.com
    - 22076

# A redis database. This database acts as the default for both
# the fnordmetric metric collection, for the resque configuration,
# and for the medium level cache - but these can be configuration
# , used for various things.
#
# Note: these URLs should end in "/"
redis:
  staging:      redis://bountyhill:8e7e2d80025989f1e163c94597437764@koi.redistogo.com:9617/
  test:         redis://localhost:6379/
  development:  redis://localhost:6379/
  live:         redis://:jN3ERLqggaP6UdTLM8RiEP8h8ZUrFwHAR8e1GeiZNf0ASrfcA6Sww8sS5tKzilvN@node-665b5a0c3f6206ab4.openredis.com:10315/

# The database URL for use with bountybase/models. Note that the database URL
# is not read from here, but
#
# - from bountyhill's config/database.yml file in "bountyhill" (the entire
#   bountybase/models part will not be used then), and
# - from bountybase's config/database.yml file during bountybase tests
#
database:
  live:         postgres://gymwlmyhwlzxcp:9dpZP-nW80R0ozq1fouvkQ-4Kg@ec2-54-243-237-247.compute-1.amazonaws.com:5432/deplol8l2rnhkb
  staging:      postgres://xfyhqfoxnpvaig:d8tYBsSKaz62fptqYXU4luFhKl@ec2-107-22-165-100.compute-1.amazonaws.com:5432/d9mdidpvdt48bj
  development:  postgres://bountyhill:bountyhill@localhost:5432/bountyhill
  
# The resque configuration. This accepts a 
#
# - a 'hostname:port' string
# - a '[0-9]+' string to select a database from the general redis configuration.
# - a '[^:]+' string to select a namespace in the generally configured redis database.
# - the "none" value to skip resque configuration.
#
# The default configuration sets a "resque" value, assuming that the redis 
# config entry is different in all environments.
resque:
  default:      resque
  deployment:   none

# The bountybase cache
cache:
  default:      bountycache

#
# choose the metrics adapter.
metrics:
  default:      stathat
  development:  dummy
  test:         dummy

# The librato metrics credentials. Even though they are the same we cannot use a "default"
# setting because development and test do not generate metrics.
#
# CURRENTLY NOT IN USE!
librato:
  deployment:
    username:   deployment@bountyhill.com
    apikey:     d903064769ddf800ce3d8b7b7dcb64c368d9b7d02ebd6c24b03c57b3ff90049b
  live:
    username:   deployment@bountyhill.com
    apikey:     d903064769ddf800ce3d8b7b7dcb64c368d9b7d02ebd6c24b03c57b3ff90049b
  staging:
    username:   deployment@bountyhill.com
    apikey:     d903064769ddf800ce3d8b7b7dcb64c368d9b7d02ebd6c24b03c57b3ff90049b

#
# Twitter authentication keys. Authentication needs consumer_* and oauth_token* values;
# urls are for reference purposes only and denote the twitter app URL. They are currently
# set on default. While this is good for bountytick, bountytwirl instances must be run 
# via separate applications.
twitter:
  default:
    development:
      url:              https://apps.twitter.com/app/6061072
      consumer_key:     c6cvEkq8dHMaTa9F2y2w
      consumer_secret:  6UdPXY4Wx9AgXH9YL65Ev3gCZgZ0lEop8ylsVRXjGE
      oauth_token:      744854762-wp6aXWnaRE6XLnD7pCy8qAyj4qo3ZYL3fy2nleI
      oauth_secret:     IhoMD0O9VRLZTwYkBPJT9jRcvd0K5kgVgVPmH5sQ
    test:
      url:              https://apps.twitter.com/app/2982201
      consumer_key:     c6cvEkq8dHMaTa9F2y2w
      consumer_secret:  6UdPXY4Wx9AgXH9YL65Ev3gCZgZ0lEop8ylsVRXjGE
      oauth_token:      744854762-wp6aXWnaRE6XLnD7pCy8qAyj4qo3ZYL3fy2nleI
      oauth_secret:     IhoMD0O9VRLZTwYkBPJT9jRcvd0K5kgVgVPmH5sQ
    twirl1:
      url:              https://apps.twitter.com/app/2982201
      consumer_key:     c6cvEkq8dHMaTa9F2y2w
      consumer_secret:  6UdPXY4Wx9AgXH9YL65Ev3gCZgZ0lEop8ylsVRXjGE
      oauth_token:      744854762-wp6aXWnaRE6XLnD7pCy8qAyj4qo3ZYL3fy2nleI
      oauth_secret:     IhoMD0O9VRLZTwYkBPJT9jRcvd0K5kgVgVPmH5sQ
    twirl2:
      url:              https://apps.twitter.com/app/2982201
      consumer_key:     hucvNtFL6gDA6t5XjlD1A
      consumer_secret:  YotJBuBSLTaP8IUhbkUU46nKPtCmcI6BFL53oaRQQI
      oauth_token:      744854762-0AOIW3nminJYWUZrThOQGpJvQYb30BeAMCLJp06S
      oauth_secret:     mnmcR4RWhR6xvMxu6yzJ3NGRf3jzdvOUQzn22Ndo
    #
    # Note: bountyclerk1 uses the same twitter account as bountytwirl2, for now.
    # This is ok during development.
    clerk1:
      url:              https://apps.twitter.com/app/2982201
      consumer_key:     hucvNtFL6gDA6t5XjlD1A
      consumer_secret:  YotJBuBSLTaP8IUhbkUU46nKPtCmcI6BFL53oaRQQI
      oauth_token:      744854762-0AOIW3nminJYWUZrThOQGpJvQYb30BeAMCLJp06S
      oauth_secret:     mnmcR4RWhR6xvMxu6yzJ3NGRf3jzdvOUQzn22Ndo
    tick:
      url:              https://apps.twitter.com/app/2982207
      consumer_key:     auDWHPRoc7egQgHsMbUjg
      consumer_secret:  9qFMRghFa5F0s06CxYvFn22mXNpmrzzrBhbrzO7FA7M
      oauth_token:      744854762-zImMVMa47UrGbmvfjHz5w3gTXeYgtMeO44GFEnMZ
      oauth_secret:     FetfXPlK0dyRhQUd98OoFDC7CQI1s17FjlGpJwRXDQ

#
# Tweets to track. In addition to these entries bountytwirl tracks the
# twitter_app.tag hashtag, i.e."#bhstaging" or "#bounty"
tracking:
  default:   
    # - Berlin
    - "@big_ben_clock"

#
# The twitter app configuration
# Note: most of the settings below are for reference only; important
# settings are user, consumer_* and oauth_token_*
#
# - twitter_app.user: The "public" twitter account. This is the account
#   owning the bountyhill twitter application.
# - twitter_app.tag: The hash tag used to mark bounties. The twirl agent
#   is configured to follow this hash tag in addition to the hash tags
#   defined in the twirl_tags settings above.
#
twitter_app:
  default:
    user:             bh_tester
    tag:              "#bh_tester"
    email:            bh-tester@bountyhill.com
    identifier:       bh_tester
    password:         3341f0d226051ece165ec0183f861714
    page_url:         http://twitter.com/bh_tester
    consumer_key:     rMpkTLPQSBzAU8bDAMpDJ6LFz
    consumer_secret:  GdrUkXYMTghJeztlRsafPWQMeOMy5sxhO01AyhhExr6FAWdKrw
    oauth_token:      1334657684-zDByTyhtcWO3YYCPtqA8NfikXoShOQW8OoS9aa4
    oauth_secret:     s4lJPp8UsxyH8lWfGhSpWYGkPm8rYgZNNtZuYy0u8i0DW
  staging:
    user:             bhstaging
    tag:              "#bhstaging"
    email:            staging@bountyhill.com
    identifier:       bhstaging
    password:         0cc7dbc46f19f6738fda47621653c51f
    page_url:         http://twitter.com/bhstaging
    consumer_key:     hpouSAo1rpoHofACKhzU4w
    consumer_secret:  PNXFsQWQT8Jpm5yBtGDP5NMjSAIP3n5At9NvGgeY2UY
    oauth_token:      834028045-4bLR1B000BqoFxt80OXW9h1xlY9Z9v1ueBO5qbBr
    oauth_secret:     bJ1Gylrg39y8x9dt7BYXLeuwLpCMNqJHMEYfnIxTU
  live:
    user:             bountyhill
    tag:              "#bounty"
    email:            info@bountyhill.com
    identifier:       bountyhill
    password:         d2fdb2b362aef57eafdf9471ee
    page_url:         http://twitter.com/bountyhill
    consumer_key:     QewZfxFwrBA6t8OGU9AqA
    consumer_secret:  m2EXPHI9MaaIhfZ46CC8Vp1b3EIJr3vSvcwGc0
    oauth_token:      610307762-ViszdmxA6yRIAbiUYaJEkHHtrMLxfm5tH1k6dxcs
    oauth_secret:     uzFmJJvBc89wTU3wLgSTUNItM0Hat5M7k7cpn9v0VA


#
# This account is used to send messages directly to bountyhill users.
# This is the account a user will be follow when signing in.
twitter_notifications:
  default:
    user:             bountyhermes
    email:            bountyhermes@bountyhill.com
    identifier:       bountyhermes
    password:         7e9447a4f162cd131c1e941cc14f861f
    url:              https://dev.twitter.com/apps/3339978/show
    consumer_key:     5Qwo5csYLfl78duu75jsBg
    consumer_secret:  RVUc2P6Rn4pje5XlYJwCekivEmbwal2FU4VwALxCrXk
    oauth_token:      857751487-DygiKejULjguoQFttG144RpIOqOUvhxp9zlBYQVj
    oauth_secret:     461RyIGIgXQPMgY9vyLuSWurgXcAhnLLPChSDFohE

#
# The facebook app configuration
# check settings with https://developers.facebook.com/tools/explorer
facebook_app:
  default:
    page_id:          389358064530268
    page_url:         http://www.facebook.com/pages/Bhdevelopment/389358064530268
    page_token:       CAAGQzyOQfRQBALCrIPBHNgZBoBc3W60psF9lx8N5dy9k5ZBxuLVOuSMu17LG8TTIxwfNeVe1kuWn3Am24hXBkjom3Hha2fAuRPpYTWBmt7ygZCOsevvPAabhySZA7DufXpUOKJ5yOCIiV6ucD1c4yC36zsHnFPyiYcQ3VWrH7jIftXzGa2MULSov2Hd4wk0ZD
    consumer_key:     440694306012436
    consumer_secret:  d70a1037d08802b21648dd3269d60e47
  staging:
    page_id:          1402962513275114
    page_url:         http://www.facebook.com/bhstaging
    page_token:       CAAHKfXcAZBhsBAO35EIx8wYXUvEMqWoivDx04wjdkrZC560IlHbsmM4Ro7zMMRdyDvugZCS3KYDDIZBm5OuDFfix1fXOqaZBrYCrGS7fsppFJ1cMuhnhh3oVNuv3wdZCxjOTMFsqA22iGuDYyhLyjulMoVndFF4utJRuXg8eCdD1q2SRoj09agHAo8DSqZCl0cZD
    consumer_key:     551612581545364
    consumer_secret:  4fb957ab281d55935b010a9219ebd95c
  live:
    page_id:          388308247883918
    page_url:         http://facebook.com/bountyhill
    page_token:       CAAHKfXcAZBhsBANLdD1bulHZAgaiz7aLWvFLJZB5rrSlMxDig5c5UEpbhmyifAD2YM8ZCcZB2sF52jbXo9ca80r3zhCNkVhPliuUCnDPmZBPkBwGTjjnw3I8Ob8dqTMfaKe4nFeFIORZBIIdwt920kSm9awrlTQxOSnlLDxUuuTdzAWLc5OLj8SNFemPwNCD78ZD
    consumer_key:     504115192986139
    consumer_secret:  f30a99860690df7d270d3dfd1ecc1de4

#
# The google+ app configuration
# for API access see: https://developers.google.com/oauthplayground
# for token information call: https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=<token>
google_app:
  default:
    name:             bhdevelopment
    page_id:          113771683784910912848
    page_url:         http://plus.google.com/113771683784910912848
    activity:         http://schemas.google.com/AddActivity
    consumer_key:     51315874974-jekf92glah32b5gngimbfe0bbq9tu9jq.apps.googleusercontent.com
    consumer_secret:  Fp2N7ace2dNGdbMYqSyDGdbG
  staging:
    name:             bhstaging
    page_id:          114340468587665009234
    page_url:         http://plus.google.com/114340468587665009234
    consumer_key:     278792493980.apps.googleusercontent.com
    consumer_secret:  WOglU7FHfWO33flL8___Tzq3
  live:
    name:             bountyhill
    page_id:          112820322074000009163
    page_url:         http://plus.google.com/112820322074000009163
    consumer_key:     751090992775.apps.googleusercontent.com
    consumer_secret:  Z0gN7gJjY45U-79brv-yTTjD

#
# The linkedin app configuration
# pls. note that for test and staging we use linkedin's general test company
# when posting to this company, no special rights are required otherwise we
# have to obtain the 'rw_company_admin' permission which is given to the linkedin user
# 'admin@bountyhill.com' within his oauth_token and oauth_secret defined below
# see: http://developer.linkedin.com/creating-company-shares
# 
# TODO: The oauth tokens and secrets below have a limited livetime of 2 month and have to be 
# renewed afterwards! Otherwise we have to define a linked in admin user and renew it's 
# authorization credentials evertime they have expired automatically
linkedin_app:
  default:
    page_id:          2414183
    page_url:         http://www.linkedin.com/company/devtestco
    consumer_key:     1em5l9vq6p0d
    consumer_secret:  NitR187uTe5AYdYU
    oauth_token:      3128144d-f392-4a83-89e1-1b251a8fbb49
    oauth_secret:     11f8a2f0-e026-4dc9-91f2-43fe68fb82ad
  staging:
    page_id:          2414183
    page_url:         http://www.linkedin.com/company/devtestco
    consumer_key:     72tkeaux4puz
    consumer_secret:  Df0ySq4yuWR8UWX9
    oauth_token:      d129e758-e262-4e5b-9c83-a451b584b827
    oauth_secret:     b7e131f2-7135-47ed-8b62-76b3a069f778
  live:
    page_id:          3549235
    page_url:         http://www.linkedin.com/company/bountyhill
    consumer_key:     gc4f48gsk6bj
    consumer_secret:  Cd7yi7pGARijTzEB
    oauth_token:      5ad8a913-4a4b-4e5d-b185-d1920a55faad
    oauth_secret:     fd3eeeb9-b668-42a6-8353-47d6a110bc06

#
# The xing app configuration
# TODO: add admin user's oauth credentials once it's possible to 
# post messages to company pages via the XING API
xing_app:
  default:
    page_id:          bountyhill
    page_url:         http://www.xing.com/companies/bountyhill
    consumer_key:     556ab78c6089fe294956 # test key only
    consumer_secret:  b23ac101bb9a04739e874ec8fc5b8a3eed6036e0
    oauth_token:      
    oauth_secret:     
  staging:
    page_id:          bountyhill
    page_url:         http://www.xing.com/companies/bountyhill
    consumer_key:     e8b1e1090cdf84189ca0
    consumer_secret:  979cc400e84233b8494906f23c6321957715180a
    oauth_token:      
    oauth_secret:     
  live:
    page_id:          bountyhill
    page_url:         http://www.xing.com/companies/bountyhill
    consumer_key:     4e2ed6e32f2b01ee1400
    consumer_secret:  e7b0acaaa4792b5c6fafe068fe53ce91fd0b92a0
    oauth_token:      
    oauth_secret:     

#
# The email identity for bountyhill's draft user
email_draft:
  default:
    email:                  draft@bountyhill.com
    password:               kjhb234cdx56öjsd89wew87sfg4fc287n443gcnr3xr2
    password_confirmation:  kjhb234cdx56öjsd89wew87sfg4fc287n443gcnr3xr2

#
# redis connection for fnordmetric statistics.
fnordmetric:
  default:
    redis_url:        redis://localhost:6379
    redis_prefix:     dev
  staging:
    redis_url:        redis://bountyhill:8e7e2d80025989f1e163c94597437764@koi.redistogo.com:9617/
    redis_prefix:     staging
  live:
    redis_url:        redis://bountyhill:8e7e2d80025989f1e163c94597437764@koi.redistogo.com:9617/
    redis_prefix:     pro

#
#
# rules.io config.
rulesio:
  default:
    disabled:         true
    token:            'yNzTq0l2F2rQxIFwfnufiA'

# The stathat account name.
stathat:
  default:            eno@open-lab.org
  live:               eno@bountyhill.com

#
#
neo4j:
  # test:               http://9e68fcc50:2bb6aea56@291fac8e1.hosted.neo4j.org:7289
  development:        http://localhost:7474
  test:               http://localhost:7474
  # The live neo4j database is from bountyhill-live-web1's "neo4j:test" addon
  live:               http://680a4d34c:e5b816c6c@a065d9bef.hosted.neo4j.org:7261
  # The staging neo4j database is from bountyhill-staging-web1's "neo4j:test" addon
  staging:            http://080d38637:9acfd4e44@a77c2239e.hosted.neo4j.org:7292

#
# Configuration for transloadit image upload. This includes both S3 storage
# configuration (bucket, key, secret) and transloadit account information.
transloadit:
  default:
    key:              17d2e6f10126475eb760488225759517
    secret:           0c3b2954e827002e1d7ac27e964bcd4eb7ad94e2
    s3_key:           183DWY3TS8SWQQJAAY82
    s3_secret:        NndG7WPbbBb3cE/X7MB797U/vIZJnxhHjYcvaH1g
  development:
    s3_bucket:        bountyhill-dev
  test:
    s3_bucket:        bountyhill-test
  staging:
    s3_bucket:        bountyhill-staging
  live:
    s3_bucket:        bountyhill-live

#
# Admin twitter uids.
# TODO: add missing uids!
admins:
  - "34037675"    # earl_oett
  - "radiospiel"  # radiospiel
  - "kaaweh"      # kaaweh

#
# The filepicker.io key.
filepicker:
  default:
    apikey:           A0STGTJHyR52MlIqmc86dz
