#
# The bountybase configuration: This is yaml.

# The syslog configuration, per environment an array of [ hostname, port ] 
syslog:
  deployment:
    - logs.papertrailapp.com
    - 61566
  production:
    - logs.papertrailapp.com
    - 11905
  staging:
    - logs.papertrailapp.com
    - 22076

# The resque configuration, one URL per environment.
# TODO: setup redis instance for production
resque:
  deployment:   none
  production:   redis://bountyhill:8e7e2d80025989f1e163c94597437764@koi.redistogo.com:9617/
  staging:      redis://bountyhill:8e7e2d80025989f1e163c94597437764@koi.redistogo.com:9617/
  test:         redis://localhost:6379/1
  development:  redis://localhost:6379/2

# The librato metrics credentials. Even though they are the same we cannot use a "default"
# setting because development and test do not generate metrics.
librato:
  deployment:
    username:   deployment@bountyhill.com
    apikey:     d903064769ddf800ce3d8b7b7dcb64c368d9b7d02ebd6c24b03c57b3ff90049b
  production:
    username:   deployment@bountyhill.com
    apikey:     d903064769ddf800ce3d8b7b7dcb64c368d9b7d02ebd6c24b03c57b3ff90049b
  staging:
    username:   deployment@bountyhill.com
    apikey:     d903064769ddf800ce3d8b7b7dcb64c368d9b7d02ebd6c24b03c57b3ff90049b

#
# Twitter authentication keys. Authentication needs consumer_* and access_token* values;
# urls are for reference purposes only and denote the twitter app URL. They are currently
# set on default. While this is good for bountytick, bountytwirl instances must be run 
# via separate applications.
twitter:
  default:
    bountytwirl1:
      url:                  https://dev.twitter.com/apps/2982201
      consumer_key:         c6cvEkq8dHMaTa9F2y2w
      consumer_secret:      6UdPXY4Wx9AgXH9YL65Ev3gCZgZ0lEop8ylsVRXjGE
      access_token:         744854762-wp6aXWnaRE6XLnD7pCy8qAyj4qo3ZYL3fy2nleI
      access_token_secret:  IhoMD0O9VRLZTwYkBPJT9jRcvd0K5kgVgVPmH5sQ
    bountytwirl2:
      url:                  https://dev.twitter.com/apps/2982201
      consumer_key:         hucvNtFL6gDA6t5XjlD1A
      consumer_secret:      YotJBuBSLTaP8IUhbkUU46nKPtCmcI6BFL53oaRQQI
      access_token:         744854762-0AOIW3nminJYWUZrThOQGpJvQYb30BeAMCLJp06S
      access_token_secret:  mnmcR4RWhR6xvMxu6yzJ3NGRf3jzdvOUQzn22Ndo
    bountytick:
      url:                  https://dev.twitter.com/apps/2982207
      consumer_key:         auDWHPRoc7egQgHsMbUjg
      consumer_secret:      9qFMRghFa5F0s06CxYvFn22mXNpmrzzrBhbrzO7FA7M
      access_token:         744854762-zImMVMa47UrGbmvfjHz5w3gTXeYgtMeO44GFEnMZ
      access_token_secret:  FetfXPlK0dyRhQUd98OoFDC7CQI1s17FjlGpJwRXDQ

#
# Listen for which tags?
twirl_tags:
  default:   
    - Berlin
    - "#Olympia2012"
    - "@big_ben_clock"
